expname: TransBTS
device_ids: [0] # single gpu

data:
  data_dir: "/content/drive/MyDrive/BrainTumorClassification/train"
  label: "/content/drive/MyDrive/BrainTumorClassification/train_labels.csv"
  mode: "train"

model:
  conv_repr: true

training:
  log_root_dir: "logs"
  val_split: 0.1
  batch_size: 4
  
  lr_param: 0.0002
  step_size: 1
  lr_annual: 0.9954

  ckpt_file: null
  ckpt_ignore_keys: []
  ckpt_only_use_keys: null

  num_ep: 1000
  